### ISSUE TITLE
PIO画面のUIがバグっている

### ISSUE THREAD

**Issue by sagiii** [YUKAI/KonashiInspector#11]
# 環境
- iPhone6
- iOS10.2.1

# 問題
konashiに接続しPIO画面を選択。
昔はPIOをスワイプしてpull-up(?)を設定できたが、いまは出来ない。
`Low | High` の右に `T...le` というラベルが表示されている。

# スクショ
![img_4941](https://cloud.githubusercontent.com/assets/3139682/25126477/6ba57ff4-246d-11e7-8ef2-35b3ecb02aa8.PNG)

**Comment by sagiii** [comment]
![img_4941](https://cloud.githubusercontent.com/assets/3139682/25126477/6ba57ff4-246d-11e7-8ef2-35b3ecb02aa8.PNG)

**Comment by 0x0c** [comment]
Toggleの文字が切れてますね、、、
文字サイズを小さくすると治ります。

**Comment by 0x0c** [comment]
https://github.com/YUKAI/KonashiInspector/commit/90ac660822a755e2c54fd9f1f2d631c6704caed5
