### ISSUE TITLE
konashi2.0のPWM動作でLEDが小刻みにチカチカする

### ISSUE THREAD

**Issue by norioike** [YUKAI/KonashiInspector#4]
konashi2.0の動作をテスト基板で行いました。
PWM の動作において、PWMをON→Period,Dutyを変えるとLEDが点灯しますが、
ある一定の明るさで点灯し続けるのではなく、かなりの頻度で点滅をします。

**Comment by norioike** [comment]
konashi Inspectorのbranch→develop

Podfileの違いにより発生する、しないの変化を確認できました。
pod 'konashi-ios-sdk', # :git => "git@github.com:YUKAI/konashi-ios-sdk.git", :branch => "feature/refactoring_ios9"
→点滅します。

pod 'konashi-ios-sdk', :git => "git@github.com:YUKAI/konashi-ios-sdk.git", :branch => "feature/refactoring_ios9"
→問題なくPWM制御をすることができました。

**Comment by 0x0c** [comment]
iOSのバージョンは9ですか？

**Comment by norioike** [comment]
iOSバージョンは9.0.1で確認しました。

**Comment by 0x0c** [comment]
ios-sdk側の問題なので、konashi-ios-sdkの改修が終わり次第対応します。

**Comment by 0x0c** [comment]
ファームウェアの問題だったらしい
