### ISSUE TITLE
Konashi Inspector のPI/O 0pinのpull upがアプリ側で変化しない

### ISSUE THREAD

**Issue by norioike** [YUKAI/KonashiInspector#5]
Konashi Inspector develop-branchのアプリでPI/O 0 pinの項目のみpull upが遷移せずcloseしてしまいます。
そのため、プルアップを確認することができませんでした。

**Comment by 0x0c** [comment]
遷移せずにcloseしてしまう、というのは具体的にどういう動作ですか？
より詳しく教えて下さい。また、再現手順と再現環境も教えて下さい。

**Comment by norioike** [comment]
再現環境:iOS9.0.1 , iPhone6 plus
Konashi1.0,Konashi2.0で発生。テスト基板を使用。     

手順ですが、
Inspectorを起動→konashiと接続→PIOタブを選択
0pinを左にスライド。"Pullup"を表示 →Pullupをタップ→サイド左にスライドして"Pullup"の表示を確認。テスト基板でも同様にLEDが点灯するかどうか確認。
という手順で行いました。

他のピンでこの動作を行うと、"NoPulls"と表示され、プルアップできていることを確認することができますが、0pinのみプルアップの確認ができませんでした。
![img_1525](https://cloud.githubusercontent.com/assets/14104069/10184098/941bc9fc-6772-11e5-9458-ac2a61b5c978.jpg)
![img_1524](https://cloud.githubusercontent.com/assets/14104069/10184100/98ca3614-6772-11e5-9cd9-842facfdd7a3.jpg)
